version: 2
updates:
- package-ecosystem: devcontainers
  directory: /
  schedule:
    interval: weekly
- package-ecosystem: npm
  directory: /
  schedule:
    interval: weekly
  versioning-strategy: increase-if-necessary
  allow:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
  cooldown:
    default-days: 7
  open-pull-requests-limit: 5
